# Generated by Django 3.2 on 2024-09-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_unique_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
    ]
