# Generated by Django 3.2 on 2024-09-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_review_unique_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title_id',
            new_name='title',
        ),
    ]
